/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GameVoteRouteImport } from './routes/game/vote'
import { Route as GameSettingsRouteImport } from './routes/game/settings'
import { Route as GameResultsRouteImport } from './routes/game/results'
import { Route as GamePlayRouteImport } from './routes/game/play'
import { Route as GameDiscussionRouteImport } from './routes/game/discussion'
import { Route as GameRevealPlayerIdRouteImport } from './routes/game/reveal.$playerId'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GameVoteRoute = GameVoteRouteImport.update({
  id: '/game/vote',
  path: '/game/vote',
  getParentRoute: () => rootRouteImport,
} as any)
const GameSettingsRoute = GameSettingsRouteImport.update({
  id: '/game/settings',
  path: '/game/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const GameResultsRoute = GameResultsRouteImport.update({
  id: '/game/results',
  path: '/game/results',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlayRoute = GamePlayRouteImport.update({
  id: '/game/play',
  path: '/game/play',
  getParentRoute: () => rootRouteImport,
} as any)
const GameDiscussionRoute = GameDiscussionRouteImport.update({
  id: '/game/discussion',
  path: '/game/discussion',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRevealPlayerIdRoute = GameRevealPlayerIdRouteImport.update({
  id: '/game/reveal/$playerId',
  path: '/game/reveal/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-to-play': typeof HowToPlayRoute
  '/players': typeof PlayersRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/game/discussion': typeof GameDiscussionRoute
  '/game/play': typeof GamePlayRoute
  '/game/results': typeof GameResultsRoute
  '/game/settings': typeof GameSettingsRoute
  '/game/vote': typeof GameVoteRoute
  '/game/reveal/$playerId': typeof GameRevealPlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-to-play': typeof HowToPlayRoute
  '/players': typeof PlayersRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/game/discussion': typeof GameDiscussionRoute
  '/game/play': typeof GamePlayRoute
  '/game/results': typeof GameResultsRoute
  '/game/settings': typeof GameSettingsRoute
  '/game/vote': typeof GameVoteRoute
  '/game/reveal/$playerId': typeof GameRevealPlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-to-play': typeof HowToPlayRoute
  '/players': typeof PlayersRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/game/discussion': typeof GameDiscussionRoute
  '/game/play': typeof GamePlayRoute
  '/game/results': typeof GameResultsRoute
  '/game/settings': typeof GameSettingsRoute
  '/game/vote': typeof GameVoteRoute
  '/game/reveal/$playerId': typeof GameRevealPlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-to-play'
    | '/players'
    | '/settings'
    | '/stats'
    | '/game/discussion'
    | '/game/play'
    | '/game/results'
    | '/game/settings'
    | '/game/vote'
    | '/game/reveal/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-to-play'
    | '/players'
    | '/settings'
    | '/stats'
    | '/game/discussion'
    | '/game/play'
    | '/game/results'
    | '/game/settings'
    | '/game/vote'
    | '/game/reveal/$playerId'
  id:
    | '__root__'
    | '/'
    | '/how-to-play'
    | '/players'
    | '/settings'
    | '/stats'
    | '/game/discussion'
    | '/game/play'
    | '/game/results'
    | '/game/settings'
    | '/game/vote'
    | '/game/reveal/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowToPlayRoute: typeof HowToPlayRoute
  PlayersRoute: typeof PlayersRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  GameDiscussionRoute: typeof GameDiscussionRoute
  GamePlayRoute: typeof GamePlayRoute
  GameResultsRoute: typeof GameResultsRoute
  GameSettingsRoute: typeof GameSettingsRoute
  GameVoteRoute: typeof GameVoteRoute
  GameRevealPlayerIdRoute: typeof GameRevealPlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/vote': {
      id: '/game/vote'
      path: '/game/vote'
      fullPath: '/game/vote'
      preLoaderRoute: typeof GameVoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/settings': {
      id: '/game/settings'
      path: '/game/settings'
      fullPath: '/game/settings'
      preLoaderRoute: typeof GameSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/results': {
      id: '/game/results'
      path: '/game/results'
      fullPath: '/game/results'
      preLoaderRoute: typeof GameResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/play': {
      id: '/game/play'
      path: '/game/play'
      fullPath: '/game/play'
      preLoaderRoute: typeof GamePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/discussion': {
      id: '/game/discussion'
      path: '/game/discussion'
      fullPath: '/game/discussion'
      preLoaderRoute: typeof GameDiscussionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/reveal/$playerId': {
      id: '/game/reveal/$playerId'
      path: '/game/reveal/$playerId'
      fullPath: '/game/reveal/$playerId'
      preLoaderRoute: typeof GameRevealPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowToPlayRoute: HowToPlayRoute,
  PlayersRoute: PlayersRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  GameDiscussionRoute: GameDiscussionRoute,
  GamePlayRoute: GamePlayRoute,
  GameResultsRoute: GameResultsRoute,
  GameSettingsRoute: GameSettingsRoute,
  GameVoteRoute: GameVoteRoute,
  GameRevealPlayerIdRoute: GameRevealPlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
